#!/bin/bash

echo 'Current governor for each CPU:'
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

echo 'Applying performance mode to all CPUs...'
echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

echo 'Governor mode after changes:'
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
